### ISSUE TITLE
Incorrect color output inside of tables

### ISSUE THREAD

**Issue by djn-ams** [AmerMathSoc/texml#261]
When TeXML encounters a `\color` command inside of math mode, inside of a table cell, it outputs the color as RGB in the generated `.css` file. ams-html is expecting hex color codes.

Here's a MWE:

```tex
\documentclass{amsart}

\usepackage{xcolor}

\begin{document}

\begin{tabular}{cc}
{\color{red}$X$} & ${\color{blue}X}$
\end{tabular}

\end{document}
```

This produces the following `.css`:

```css
.texml-c { color: #ff0000 }
.texml-pl { padding-left: 5.0pt }
.texml-pr { padding-right: 5.0pt }
.texml-tac { text-align: center }
.texml-c1 { color: [RGB]{0, 0, 255} }
.texml-bcc { border-collapse: collapse }
```
